=== GeekchanskiY/Markup_languges_labs/lab11/xml3.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="BODY">
        <xs:complexType>
			<xs:sequence>
                <xs:element name="HED">
                    <xs:complexType>
						<xs:sequence>
                            <xs:element name="to" type="string "/>
                            <xs:element name="from" type="string "/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SMTH">
                    <xs:complexType>
			            <xs:sequence>
                            <xs:element name="main" type="string "/>
                            <xs:element name="cells" type="string "/>
                            <xs:element name="cells" type="string "/>
                            <xs:element name="cells" type="string "/>
                            <xs:element name="cells" type="string "/>
                            <xs:element name="cells" type="string "/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="epilogue" type="string "/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GeekchanskiY/Markup_languges_labs/lab11/xml3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="styles.css"?>
<BODY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml3.xsd">
<HED>
<to>To: Me.</to>
<from>From: My Mind.</from>
</HED>
<SMTH>
<main>The main priorities to me.</main>
<cells>1. Eat food</cells>
<cells>2. Sing songs</cells>
<cells>3. Feel smell</cells>
<cells>4. Sleep well</cells>
<cells>5. Study good</cells>
</SMTH>
<epilogue>Thanks for your attention.</epilogue>
</BODY>
